import VueRouter from 'vue-router';

let routes = [
    { path: '/', component: require('./components/admin/Dashboard.vue').default },
    { path: '/dashboard', component: require('./components/admin/Dashboard.vue').default },
    { path: '/admin_dashboard', component: require('./components/admin/AdminDashboard.vue').default },
    { path: '/category', component: require('./components/admin/Category.vue').default },
    { path: '/brand', component: require('./components/admin/Brand.vue').default },
    { path: '/attribute', component: require('./components/admin/Attribute.vue').default },
    { path: '/size', component: require('./components/admin/Size.vue').default },
    { path: '/color', component: require('./components/admin/Color.vue').default },
    { path: '/admin_category', component: require('./components/admin/AdminCategory.vue').default },
    { path: '/category/:category/slab', component: require('./components/admin/CategoryDeliverySlab.vue').default },
    { path: '/category/:category/cat', component: require('./components/admin/CategoryCat.vue').default },
    { path: '/admin_category/:category/subcat', component: require('./components/admin/AdminSubCategory.vue').default },
    { path: '/sub_category', component: require('./components/admin/SubCategory.vue').default },
    { path: '/subCategory/:category/cat', component: require('./components/admin/SubCategoryCat.vue').default },
    { path: '/mst_package', component: require('./components/admin/Package.vue').default },
    { path: '/marketing_box', component: require('./components/admin/MarketingBox.vue').default },
    { path: '/delivery_charges', component: require('./components/admin/DeliveryCharges.vue').default },
    { path: '/offer_product', component: require('./components/admin/OfferProduct.vue').default },
    { path: '/product', component: require('./components/admin/Product.vue').default },
    { path: '/admin_product', component: require('./components/admin/AdminProduct.vue').default },
    { path: '/vendors', component: require('./components/admin/Vendor.vue').default },
    { path: '/topvendor', component: require('./components/admin/TopVendor.vue').default },
    // { path: '/superadmin', component: require('./components/admin/SuperAdmin.vue').default },
    { path: '/vendor_products/:vendor', component: require('./components/admin/VendorProduct.vue').default },
    { path: '/vendor_products/:vendor/bulk_assign', component: require('./components/admin/VendorProductBulkAssign.vue').default },
    { path: '/admin_service_area', component: require('./components/admin/AdminServiceArea.vue').default },
    { path: '/service_area_products/:vendor', component: require('./components/admin/AdminServiceAreaProduct.vue').default },
    { path: '/service_area_products/:vendor/bulk_assign', component: require('./components/admin/AdminServiceAreaProductBulkAssign.vue').default },
    { path: '/service_area/', component: require('./components/admin/ServiceArea.vue').default },
    { path: '/orders', component: require('./components/admin/Orders.vue').default },
    { path: '/getorders', component: require('./components/admin/GetOrder.vue').default },
    { path: '/admin_orders', component: require('./components/admin/AdminOrders.vue').default },
    { path: '/delivery_person/:deliveryPerson/commodity', component: require('./components/admin/DeliveryPersonCommodities.vue').default },
    { path: '/marketing_person', component: require('./components/admin/MarketingPerson.vue').default },
    { path: '/coupon', component: require('./components/admin/Coupon.vue').default },
    { path: '/Suggession', component: require('./components/admin/Suggession.vue').default },
    { path: '/commodity', component: require('./components/admin/Commodity.vue').default },
    { path: '/delivery_wallet/:deliveryPersonId', component: require('./components/admin/DeliveryPersonWallet.vue').default },
    { path: '/marketing_wallet/:marketingPersonId', component: require('./components/admin/MarketingPersonWallet.vue').default },
    { path: '/vendor_wallet/:vendorId', component: require('./components/admin/VendorWallet.vue').default },
    { path: '/splash', component: require('./components/admin/Splash.vue').default },
    { path: '/report/orders', component: require('./components/admin/reports/OrderReport.vue').default },
    { path: '/report/delivery_wallet', component: require('./components/admin/reports/DeliveryWallet.vue').default },
    { path: '/report/vendor_wallet', component: require('./components/admin/reports/VendorWallet.vue').default },
    { path: '/report/franchisee_report', component: require('./components/admin/reports/FranchiseeReport.vue').default },
    { path: '/report/franchisee_wallet', component: require('./components/admin/reports/FranchiseeWallet.vue').default },
   // { path: '/franchisee_wallet', component: require('./components/admin/FranchiseeWallet.vue').default },
    { path: '/report/marketing_wallet', component: require('./components/admin/reports/MarketingWallet.vue').default },
    { path: '/report/item_wise', component: require('./components/admin/reports/ItemWiseReport.vue').default },
    { path: '/report/profit', component: require('./components/admin/reports/ProfitReport.vue').default },
    { path: '/customer', component: require('./components/admin/Customer.vue').default },
    { path: '/earning', component: require('./components/admin/Earning.vue').default },
    { path: '/Franchisee', component: require('./components/admin/Franchisee.vue').default },


    // aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    { path: '/purchase', component: require('./components/admin/Purchase.vue').default },
    { path: '/AddPurchaseVendor', component: require('./components/admin/PurchaseVendor.vue').default },
    { path: '/VendorManagement', component: require('./components/admin/PurchaseVendorList.vue').default },
    { path: '/purchasemanagement', component: require('./components/admin/PurchaseManagement.vue').default },
    { path: '/addproduct', component: require('./components/admin/AddProduct.vue').default },
    // newani
    { path: '/vAddCustomer', component: require('./components/admin/vAddCustomer.vue').default },
    { path: '/vAddDeliveryBoy', component: require('./components/admin/vAddDeliveryBoy.vue').default },
    { path: '/vSendFirePushNotiSetting', component: require('./components/admin/vSendFirePushNotiSetting.vue').default },
    { path: '/vPayGatewaySetting', component: require('./components/admin/vPayGatewaySetting.vue').default },
    { path: '/vSettleGateApiSetting', component: require('./components/admin/vSettleGateApiSetting.vue').default },
    { path: '/delivery_person', component: require('./components/admin/DeliveryPerson.vue').default },
    { path: '/vAddBanner', component: require('./components/admin/vAddBanner.vue').default },
    { path: '/vAddBottomBanner', component: require('./components/admin/vAddBottomBanner.vue').default },
    { path: '/TopBannerList', component: require('./components/admin/TopBannerList.vue').default },
    { path: '/BottomBannerList', component: require('./components/admin/BottomBannerList.vue').default },
    { path: '/OrderManagement', component: require('./components/admin/OrderManagement.vue').default },
    { path: '/OnlineOrderManagement', component: require('./components/admin/OnlineOrderManagement.vue').default },
    { path: '/OrderDetailsManagement/:OrderId', component: require('./components/admin/OrderDetailsManagement.vue').default },
    { path: '/Invoice/:OrderId', component: require('./components/admin/invoice.vue').default },
    { path: '/InvoicePrint/:OrderId', component: require('./components/admin/invoicenew.vue').default },
    { path: '/Invoicethermal/:OrderId', component: require('./components/admin/invoicethermal.vue').default },
    { path: '/VendorSetting', component: require('./components/admin/VendorSetting.vue').default },
    { path: '/vAddDeliveryBoy', component: require('./components/admin/vAddDeliveryBoy.vue').default },
    { path: '/ViewPurchase', component: require('./components/admin/ViewPurchase.vue').default },
    { path: '/ViewPurchaseDetails/:OrderId/vendor/:VendorId', component: require('./components/admin/ViewPurchaseDetails.vue').default },
    { path: '/stockmanagement', component: require('./components/admin/StockManagement.vue').default },
    { path: '/Showstock', component: require('./components/admin/ShowStock.vue').default },
    { path: '/editCustomer/:OrderId', component: require('./components/admin/editCustomer.vue').default },
    { path: '/ViewCustomer/:OrderId', component: require('./components/admin/ViewCustomer.vue').default },
    { path: '/editDeliveryBoy/:OrderId', component: require('./components/admin/editDeliveryBoy.vue').default },
    { path: '/DeliveryManagement/:OrderId', component: require('./components/admin/DeliveryManagement.vue').default },
    { path: '/editProduct/:OrderId', component: require('./components/admin/editProduct.vue').default },
    { path: '/editPurchaseVendor/:OrderId', component: require('./components/admin/editPurchaseVendor.vue').default },
    { path: '/RemoveStock', component: require('./components/admin/RemoveStock.vue').default },
    { path: '/MakeBill', component: require('./components/admin/MakeBill.vue').default },
    { path: '/makeabill', component: require('./components/admin/MakeaBill.vue').default },
    { path: '/ProductRecomend', component: require('./components/admin/ProductRecomend.vue').default },
    { path: '/OrderEditManagement/:OrderId', component: require('./components/admin/OrderEditManagement.vue').default },
    { path: '/GstReport', component: require('./components/admin/GstReport.vue').default },
    { path: '/gstRebateReport', component: require('./components/admin/GSTRebateReport.vue').default },
    { path: '/getsalenewreport', component: require('./components/admin/SaleReportNew.vue').default },
    
    { path: '/HsnReport', component: require('./components/admin/HsnReport.vue').default },
    { path: '/PurchaseGstReport', component: require('./components/admin/PurchaseGstReport.vue').default },
    { path: '/DayBookReport', component: require('./components/admin/DayBookReport.vue').default },
    { path: '/SaleReport', component: require('./components/admin/SaleReport.vue').default },
    { path: '/detailsaleReport', component: require('./components/admin/DetailSaleReport.vue').default },
    { path: '/PaySaleReport', component: require('./components/admin/PaySaleReport.vue').default },
    { path: '/UserOrderReport', component: require('./components/admin/UserOrderReport.vue').default },
    { path: '/SaleProductReport', component: require('./components/admin/SaleProductReport.vue').default },
    { path: '/ProfitReport', component: require('./components/admin/ProfitReport.vue').default },
    { path: '/OverallDayReport', component: require('./components/admin/OverallDayReport.vue').default },
    { path: '/ViewProduct/:OrderId', component: require('./components/admin/ViewProduct.vue').default },
    
    //admin
    { path: '/AdminVendorManagement', component: require('./components/admin/AdminVendorManagement.vue').default },
    { path: '/AdminAddVendor', component: require('./components/admin/AddVendor.vue').default },
    { path: '/EditVendor/:OrderId', component: require('./components/admin/EditVendor.vue').default },
   
    { path: '/adminaddCustomer', component: require('./components/admin/adminaddCustomer.vue').default },
    { path: '/admineditCustomer/:OrderId', component: require('./components/admin/admineditCustomer.vue').default },
    { path: '/CustomerManagement', component: require('./components/admin/AdminCustomerManagement.vue').default },
    { path: '/AdminViewCustomer/:OrderId', component: require('./components/admin/AdminViewCustomer.vue').default },
 
    { path: '/adminAddDeliveryBoy', component: require('./components/admin/adminAddDeliveryBoy.vue').default },
    { path: '/DeliveryBoyManagement', component: require('./components/admin/AdminDeliveryBoyManagement.vue').default },
    { path: '/admineditDeliveryBoy/:OrderId', component: require('./components/admin/admineditDeliveryBoy.vue').default },
    { path: '/AdminViewCustomer/:OrderId', component: require('./components/admin/AdminViewCustomer.vue').default },


]    
export default new VueRouter({
    mode:'history',
    routes
});
